package domains

const (
	VendorOpenAI              = "openai"
	VendorGoogle              = "google"
	VendorAnthropic           = "anthropic"
	ProductCodex              = "codex"
	ProductGemini             = "gemini"
	ProductClaudeCode         = "claude_code"
	CredentialOAuth           = "oauth"
	ProtocolOpenAIResponses   = "openai_responses"
	ProtocolAnthropicMessages = "anthropic_messages"

	AccountStatusAvailable = "available"
	AccountStatusLimited   = "limited"
	AccountStatusCooldown  = "cooldown"
	AccountStatusExhausted = "exhausted"
	AccountStatusDisabled  = "disabled"
	AccountStatusExpired   = "expired"
	AccountStatusInvalid   = "invalid"
	AccountStatusUnknown   = "unknown"

	QuotaStatusAvailable = "available"
	QuotaStatusLimited   = "limited"
	QuotaStatusExhausted = "exhausted"
	QuotaStatusUnknown   = "unknown"

	TokenStatusActive        = "active"
	TokenStatusRefreshNeeded = "refresh_needed"
	TokenStatusRefreshFailed = "refresh_failed"
	TokenStatusInvalid       = "invalid"

	ErrorAuthFailed         = "auth_failed"
	ErrorRateLimited        = "rate_limited"
	ErrorQuotaExhausted     = "quota_exhausted"
	ErrorUpstreamTimeout    = "upstream_timeout"
	ErrorUpstreamHTTP4xx    = "upstream_http_4xx"
	ErrorUpstreamHTTP5xx    = "upstream_http_5xx"
	ErrorUpstreamFailed     = "upstream_failed"
	ErrorStreamIncomplete   = "stream_incomplete"
	ErrorClientDisconnected = "client_disconnected"
	ErrorProtocol           = "protocol_error"
	ErrorNetwork            = "network_error"
	ErrorInternal           = "internal_error"
	// ErrorUpstream5xx 保留用于兼容升级前的历史调用记录。
	ErrorUpstream5xx        = "upstream_5xx"
	ErrorModelNotSupported  = "model_not_supported"
	ErrorNoAvailableAccount = "no_available_account"
	ErrorPlatformKeyInvalid = "platform_key_invalid"
	ErrorPlatformKeyLimited = "platform_key_limited"
)
